### ISSUE TITLE
Issues with Images

### ISSUE THREAD

**Issue by EffeArts** [ndasilver/food_delivery#42]
- Images are appearing after adding them and then disappear at a certain point

**Comment by ndasilver** [comment]
is it from the category or the menu?
if you have an example you can explain more for me to get it right.

I think it is because we are using the same database but not the same storage.
**for example:** If my image is not showing, I will try to edit and put a new image that will update my new image directory in the database but not sync with both of our directories.

**Comment by EffeArts** [comment]
I think I might have found the cause. It might be because of un-merged branches.
Like for example if I upload images while I am in a certain branch and I checkout I won't be able to see them in another branch until I merge both of them.

**Comment by ndasilver** [comment]
Yes, by pushing the changes to GitHub and pulling from the current branch can solve the issue as git hub tracks changes in the directory. I happened the other time when I migrated to the new database and I tried to create new products. when I upload an image, for you to be able to see the image, you are going to wait for me to push, otherwise, you can't see the image, even if you try to edit the category/menu you are going to see the image but I lose it too. but maybe the more we keep on pushing it might resolve the issue completely or not but that is the cause.

**Comment by EffeArts** [comment]
Now I understand. I think It's time we closed it.
